version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-crm-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-crm
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_DATABASE=laravel_crm
      - DB_USERNAME=laravel_crm
      - DB_PASSWORD=secret
      - REDIS_HOST=redis

  webserver:
    image: nginx:alpine
    container_name: laravel-crm-webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/nginx/ssl/
    networks:
      - laravel-crm
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel-crm-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_crm
      MYSQL_USER: laravel_crm
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-crm

  redis:
    image: redis:alpine
    container_name: laravel-crm-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - laravel-crm

  mailhog:
    image: mailhog/mailhog
    container_name: laravel-crm-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel-crm

networks:
  laravel-crm:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
